events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    client_max_body_size 10M;

    limit_req_zone $binary_remote_addr zone=mylimit:10m rate=50r/s;

    server {
        listen 80;
        server_name api.kasheng.dev www.kasheng.api; 

        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name api.kasheng.dev www.kasheng.api; 

        ssl_certificate /etc/ssl/certs/origin.pem;
        ssl_certificate_key /etc/ssl/private/origin.key;
 
        location /api/ {
            limit_req zone=mylimit burst=200 nodelay;
            proxy_pass http://shuttle-backend:8080;
        }

        location /ws-endpoint {
            limit_req zone=mylimit burst=20 nodelay;
            proxy_pass http://shuttle-backend:8080;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
        }

        location /pgadmin/ {
            limit_req zone=mylimit burst=5 nodelay;
            proxy_set_header X-Script-Name /pgadmin;
            proxy_set_header Host $host;
            proxy_pass http://pgadmin:80/;
            proxy_redirect off;
        }
    }
}
